[package]
name = "tigris-emoji"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = "0.7.1"
emojis = "0.6.4"
sniffer-rs = "1.1.2"
tigris-rs = { path = "/home/lighttigerxiv/projects/whiskers-apps/tigris-rs", features = [
    "extension",
] }
